############# English navigation ##############

# main menu
[[main]]
name = "For You"
weight = 1
hasChildren = true

[[main]]
parent = "For You"
name = "Individuals"
pageRef = "/Individuals"

[[main]]
parent = "For You"
name = "Developers"
pageRef = "/Developers"

[[main]]
parent = "For You"
name = "European Commission"
pageRef = "/EC"

[[main]]
weight = 2
name = "Consortium"
hasChildren = true

[[main]]
parent = "Consortium"   
name = "Open Internet Discourse"
pageRef = "/OID"

[[main]]
parent = "Consortium"   
name = "NLnet"
pageRef = "/NLnet"

[[main]]
parent = "Consortium"   
name = "Tweag"
pageRef = "/Tweag"

[[main]]
parent = "Consortium"   
name = "NORDUnet"
pageRef = "/NORDUnet"

[[main]]
weight = 3
name = "Fediversity"
pageRef = "Fediversity"

[[main]]
weight = 4
name = "Grants"
pageRef = "Grants"

[[main]]
weight = 5
name = "Events"
pageRef = "Events"

[[main]]
weight = 6
name = "News"
pageRef = "Blog"




# footer menu
[[footer]]
name = "About"
pageRef = "fediversity"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
