name: Tests
on:
  pull_request:
  push:
    branches: main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix-shell --run tests
